# Generated by Django 3.2.7 on 2021-09-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('id_chain', models.PositiveIntegerField(unique=True, verbose_name='Id Chain')),
            ],
            options={
                'verbose_name': 'Evolution Chain',
                'verbose_name_plural': 'Evolution Chains',
                'ordering': ['id_chain'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('id_pokemon', models.PositiveIntegerField(unique=True, verbose_name='Id Pokemon')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.CharField(blank=True, max_length=150, null=True, verbose_name='Image')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.evolutionchain')),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('base', models.PositiveIntegerField(verbose_name='Base stat')),
                ('effort', models.PositiveIntegerField(verbose_name='effort')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
            options={
                'verbose_name': 'Base Stat',
                'verbose_name_plural': 'Base Stats',
            },
        ),
    ]
